#ifndef C_CHAT_SERVER_LOADER_H
#define C_CHAT_SERVER_LOADER_H

#include <stddef.h>

#define DEFAULT_PORT 8080
#define MAX_CLIENTS 10
#define LISTEN_BACKLOG MAX_CLIENTS
#define READ_BUFFER_SIZE 4096
#define MAX_PENDING_BYTES (64U * 1024U)
#define MAX_MESSAGE_LENGTH 4096
#define MAX_USERNAME_LENGTH 24
#define MAX_PASSWORD_LENGTH 128
#define AUTHENTICATION_TIMEOUT_SECONDS 15
#define POLL_INTERVAL_MILLISECONDS 1000
#define PROTOCOL_VERSION "CCHAT/1"

#endif
